name: "Publish Release"

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/android-setup

      - name: Publish
        run: ./gradlew :firebase:publishReleasePublicationToReleaseRepository
